packages:
  - '.'
overrides:
  '@better-auth/core': 1.7.6
allowBuilds:
  '@prisma/engines': true
  electron: true
  electron-winstaller: false
  esbuild: true
  prisma: true
  uiohook-napi: true
minimumReleaseAgeExclude:
  - electron@44.5.1
