/** Canonical desktop copy. Other catalogs must implement every key and parameter. */
export const english = {
  microphone: 'Microphone',
  microphoneDescription:
    'Choose the microphone Tro uses for voice instructions. Voice instructions are captured while you hold the talk shortcut. You can also start a local sound test below.',
  microphoneChoose: 'Audio input',
  microphoneInputCount: (count: number): string => `${String(count)} microphone inputs`,
  microphoneAuto: 'Auto-detect',
  microphoneAutoHint: 'Follows the input selected in your computer settings.',
  microphoneUnnamed: 'Microphone',
  microphoneSuggested: 'Suggested',
  microphoneWiredHint: 'Appears to be wired or USB. A useful starting point for voice input.',
  microphoneBuiltInHint:
    'Appears to be built in. A useful starting point without a wireless connection.',
  microphoneBluetoothHint: 'Appears to be Bluetooth. Wireless startup and audio quality can vary.',
  microphoneVirtualHint:
    'Appears to be a virtual input. Check that it routes your voice rather than computer audio.',
  microphoneUnknownHint: 'Try this input if it is the microphone you normally speak into.',
  microphoneRecommendationHint:
    'Suggestions use device names, not a sound test. The best choice depends on your setup and surroundings.',
  microphoneNextHoldHint:
    'Your choice is saved on this device and applies to the next hold. Opening this list does not record audio.',
  microphonePermissionHint:
    'No named inputs yet. Hold the talk shortcut once to allow microphone access, then refresh. Also check microphone permission in your computer settings.',
  microphoneUnavailable:
    'Your selected microphone is unavailable. Reconnect it, choose another input, or select Auto-detect. Tro will not silently switch inputs.',
  microphoneListError: 'Could not list microphones. Check OS microphone access and try refreshing.',
  microphoneStorageWarning:
    'Your microphone preferences work for this session but could not be saved on this device.',
  microphoneVoiceError:
    'Voice input could not start or finish. Check your microphone and OS permission, then try again.',
  microphoneRetryVoice: 'Retry voice startup',
  microphoneSignInHint: 'Sign in to choose a microphone.',
  microphoneRefresh: 'Refresh inputs',
  microphoneDone: 'Done',
  microphonePreferred: 'Preferred',
  microphoneEditRanking: 'Edit ranking',
  microphoneResetRanking: 'Reset ranking',
  microphoneRankingHint:
    'Your first available ranked input is preferred. Ranking does not change your selected microphone or Auto-detect.',
  microphoneMoveUp: (name: string): string => `Move ${name} up`,
  microphoneMoveDown: (name: string): string => `Move ${name} down`,
  microphoneCompare: 'Compare microphones',
  microphoneTestPrivacy:
    'Tests open one microphone for six seconds. Sound is measured on this device, never uploaded or saved. Close this dialog or cancel to stop.',
  microphoneTestInstructions:
    'For each input: stay quiet for two seconds, then speak the same phrase for four seconds. Keep your position and surroundings the same. Hold-to-talk is paused during a test.',
  microphoneTestPhrase: '“This is a microphone test. I want my voice to sound clear.”',
  microphoneTestDevice: (name: string): string => `Test ${name}`,
  microphoneTestOpening: 'Opening microphone…',
  microphoneTestQuiet: 'Stay quiet',
  microphoneTestSpeak: 'Speak now',
  microphoneTestCancel: 'Cancel test',
  microphoneTestBusy: 'Finish the current voice instruction or task before testing.',
  microphoneTestError:
    'The test could not finish. Check microphone access and the connected input, then try again.',
  microphoneTestLimitations:
    'Lower quiet noise and less clipping can help. Louder speech is not always better. These levels include device processing and do not measure transcription accuracy. Choose or rank an input yourself; results clear when devices change or you sign out.',
  microphoneNoise: 'Quiet noise',
  microphoneSpeech: 'Speech level',
  microphoneClipping: 'Clipping',
  microphoneStartup: 'Startup',
  microphoneChange: 'Choose microphone',

  taskSucceeded: 'Task completed',
  taskPartial: 'Partially completed',
  taskBlocked: 'Unable to continue',
  taskUnverified: 'Result not confirmed',
  navigation: 'Main navigation',
  workspace: 'Workspace',
  settings: 'Settings',
  yourAccount: 'Your account',
  checkingSignIn: 'Checking sign-in…',
  signOut: 'Sign out',
  ownWorkspace: 'Your own little workspace',
  signInInvitation: 'Sign in to make it yours.',
  signIn: 'Sign in',
  yourDesktop: 'YOUR DESKTOP',
  attention: 'Something needs attention',
  settingsDescription: 'The essentials, all in one place.',
  account: 'Account',
  name: 'Name',
  email: 'Email',
  signOutHint: 'You can sign out from the sidebar.',
  accountSignInHint: 'Sign in from the sidebar to see your account.',
  appearance: 'Appearance',
  appearanceDescription: 'A simple, warm light theme.',
  light: 'Light',
  language: 'Language',
  languageDescription:
    'Choose the language Tro uses. Changes apply immediately and are saved on this device.',
  languageStorageWarning: 'The language changed for now, but could not be saved on this device.',
  assistant: 'Computer-use assistant',
  welcome: (name: string): string => `Welcome back, ${name}`,
  workspaceHeading: 'A little space to do more.',
  workspaceDescription: 'Your desktop, with a helping hand.',
  taskMode: 'How Tro helps',
  showMe: 'Show me',
  doIt: 'Do it for me',
  stopTask: 'Stop',
  teachingDisclosure:
    'Tro shows visual previews while you control your mouse and keyboard. It may focus an existing app. Screen observations sent to OpenAI leave your computer. Guidance currently supports the main display on macOS.',
  errorCompanionUnavailable:
    'Cursor guidance is unavailable. Update or reinstall Tro, then try again.',
  newTask: 'New task',
  makeYourselfAtHome: 'Make yourself at home.',
  googleInvitation: 'Sign in to start a task with Tro. Google opens in your browser.',
  waitingForGoogle: 'Waiting for Google…',
  continueWithGoogle: 'Continue with Google',
  helpHeading: 'What can I help you with?',
  helpDescription: 'Ask a question or tell Tro what you’d like to do in an app on your desktop.',
  conversation: 'Conversation',
  you: 'You',
  yourMessage: 'Your message',
  messagePlaceholder: 'Ask Tro to help with something…',
  working: 'Tro is working on your desktop…',
  freshStart: 'A fresh start with every message',
  sendToTro: 'Send to Tro',
  send: 'Send',
  taskDisclosure:
    'Tro may view your screen and use your mouse or keyboard. Screen observations sent to OpenAI leave your computer. Each message is a fresh task; this display clears when you close the app.',
  errorCheckSignIn: 'Could not check sign-in. Please try signing in again.',
  errorSignInTimeout: 'Google sign-in did not finish. Please try again.',
  errorOpenGoogle: 'Could not open Google sign-in.',
  errorClearTask: 'Could not clear the task. Please try again.',
  errorStartTask: 'Could not start a task. Please try again.',
  errorDailyModelLimit: 'Today’s model allowance is used up. Try again after the daily reset.',
  errorCompleteTask: 'Could not complete the task. Check the connection and desktop access.',
  errorContactAgent: 'Could not contact the local agent. Try sending again.',
  errorSignOut: 'Could not sign out. Please try again.',
  errorSignInService: 'Could not reach the sign-in service.',
  errorGoogleConfiguration: 'Google sign-in is not configured on the backend yet.',
  errorSignInRequired: 'Sign in to use Tro.',
  errorTaskBusy: 'Wait for the current task to finish.',
  errorAgentActive: 'An agent session is already active.',
  errorAgentStopped: 'The agent session ended. Start a new task.',
  errorAgentTimeout: 'The agent request timed out. Please try again.',
  guidanceDemonstrated: 'Guide finished',
  guidanceExplained: 'Explanation',
  guidanceNeedsInput: 'Your input is needed',
  guidanceCanceled: 'Guide stopped',
  guidanceFailed: 'Guide could not finish',
  guidanceNeedsInputMessage:
    'Tro could not show this step. Check that the target is visible on your primary display, then send a new request.',
  guidanceCanceledMessage: 'The guide stopped. Send a new request when you want to continue.',
  guidanceFailedMessage: 'Tro could not finish the visual guide. Send a new request to try again.',
  errorDesktopPermissions:
    'Desktop control could not start. Allow Tro Screen Recording and Accessibility in System Settings, then try again.',
  errorDesktopStart:
    'Desktop control could not start. Restart Tro or reinstall the desktop app, then try again.',
  errorInvalidRequest: 'This request is invalid. Please try again.',
  errorWindowAccess: 'This window cannot access this action. Restart Tro and try again.',
  permissionSetup: 'Desktop permission setup',
  permissionProgress: 'Setup step 2 of 3',
  permissionMacAccess: '2 Mac access',
  permissionReady: '3 Ready',
  permissionOneTimeSetup: 'ONE-TIME SETUP',
  permissionHeading: 'Give Tro access to your desktop.',
  permissionIntroduction:
    'Tro needs two macOS permissions to see your screen and help in apps. You control these in System Settings.',
  permissionTitle: 'Desktop permissions',
  permissionBothNeeded: 'Both are needed for desktop help',
  permissionAccessibility: 'Accessibility',
  permissionAccessibilityDescription: 'Lets Tro interact with the app you are using.',
  permissionScreenRecording: 'Screen Recording',
  permissionScreenRecordingDescription: 'Lets Tro see what is on your screen.',
  permissionEnabled: 'Enabled',
  permissionMissing: 'Not enabled',
  permissionUnknown: 'Not verified',
  permissionOpenSettings: 'Open Settings',
  permissionRequest: 'Ask for permission',
  permissionCheckAgain: 'Check again',
  permissionChecking: 'Checking Tro…',
  permissionReturnHint:
    'After enabling both switches, return to Tro and it will check again automatically.',
  permissionRestartHint:
    'You may need to quit and reopen Tro after changing Screen Recording. Tro will wait to start the agent until access is verified.',
  permissionVerifyError: 'Could not verify Tro permissions. Try again.',
  permissionSettingsHint:
    'In System Settings, enable Tro for both permissions, then return to Tro. Development builds may appear as Electron.',
  permissionRequestError: 'Could not open macOS permission setup. Open System Settings manually.',
  permissionOpenError: 'Could not open System Settings. Open Privacy & Security manually.',
};

export type TranslationCatalog = {
  [Key in keyof typeof english]: (typeof english)[Key];
};

export type TranslationKey = {
  [Key in keyof TranslationCatalog]: TranslationCatalog[Key] extends string ? Key : never;
}[keyof TranslationCatalog];
