import { DesktopLocale } from '#contracts/DesktopLocale.js';
import { readClassroomMessages } from '../../localization/ClassroomMessages.js';

import type { TranslationCatalog } from './English.js';

export const vietnamese = {
  ...readClassroomMessages(DesktopLocale.VIETNAMESE),
  switchAccount: 'Chuyển tài khoản',
  savedAccounts: 'Tài khoản trên máy này',
  currentAccount: 'Hiện tại',
  addAccount: 'Thêm tài khoản',
  signOutCurrentAccount: 'Đăng xuất tài khoản này',
  accountTeacher: 'Giáo viên',
  accountStudent: 'Học sinh',
  accountRoleUnknown: 'Tài khoản',
  accountExpired: 'Đăng nhập lại',
  accountSignInHeading: 'Thêm tài khoản',
  accountSignInDescription:
    'Đăng nhập bằng tài khoản Google khác. Tài khoản hiện tại vẫn được lưu trên máy này.',
  accountContinueGoogle: 'Tiếp tục với Google',
  accountWaitingGoogle: 'Hoàn tất đăng nhập trong trình duyệt.',
  accountCancelSignIn: 'Hủy đăng nhập',
  accountCancel: 'Hủy',
  accountCloseMenu: 'Đóng danh sách tài khoản',
  accountSwitching: 'Đang chuyển tài khoản…',
  accountChoose: 'Chọn tài khoản đã lưu',
  accountStorageHint: 'Phiên đăng nhập được mã hóa trên máy này.',
  errorSavedAccounts: 'Không thể tải tài khoản đã lưu. Hãy thử lại.',
  errorSwitchAccount: 'Không thể chuyển tài khoản. Hãy thử lại.',
  errorAccountExpired: 'Phiên đăng nhập đã hết hạn. Thêm lại tài khoản bằng Google.',
  errorAccountStorage:
    'Không thể truy cập kho tài khoản bảo mật. Kiểm tra quyền truy cập chuỗi khóa hệ thống rồi khởi động lại Tro.',
  errorAccountLimit:
    'Có thể lưu tối đa 10 tài khoản. Đăng xuất một tài khoản trước khi thêm tài khoản khác.',
  errorAccountBusy: 'Hoàn tất tác vụ, tải tài liệu hoặc kiểm tra micrô trước khi chuyển tài khoản.',
  voiceover: 'Đọc hướng dẫn thành tiếng',
  voiceoverDescription: 'Đọc hướng dẫn HUD bằng ngôn ngữ đã chọn qua dịch vụ giọng nói trực tuyến.',
  voiceoverUnavailable: 'Giọng nói không khả dụng. Hướng dẫn trực quan vẫn tiếp tục.',
  voiceoverStop: 'Dừng đọc',
  updateTro: 'Cập nhật Tro',
  updateAvailable: (version: string): string => `Đã có phiên bản ${version}`,
  updateDownloading: 'Đang tải…',
  updateKeepUsing: 'Tiếp tục dùng Tro',
  updateRestart: 'Khởi động lại để cập nhật',
  updateReady: (version: string): string => `Phiên bản ${version} đã sẵn sàng`,
  updateRestarting: 'Đang khởi động lại…',
  updateInstalling: 'Đang cài bản cập nhật',
  updateRetry: 'Thử cập nhật lại',
  updateRetryRestart: 'Thử khởi động lại',
  updateCheckFailed: 'Không thể kiểm tra bản cập nhật.',
  updateDownloadFailed: 'Tải thất bại. Vui lòng thử lại.',
  updateInstallFailed: 'Không thể cài đặt. Vui lòng thử lại.',
  updateProgress: 'Tiến độ tải bản cập nhật',
  updateBusy: 'Chờ tác vụ hoặc ghi âm hiện tại hoàn tất.',
  updateUnavailable: 'Không thể bắt đầu cập nhật. Vui lòng thử lại.',
  microphone: 'Micrô',
  microphoneDescription:
    'Chọn micrô Tro dùng cho yêu cầu bằng giọng nói. Thu lệnh khi bạn giữ phím tắt nói; bạn cũng có thể bắt đầu bài thử âm thanh cục bộ bên dưới.',
  microphoneChoose: 'Thiết bị thu âm',
  microphoneInputCount: (count: number): string => `${String(count)} thiết bị thu âm`,
  microphoneAuto: 'Tự động chọn',
  microphoneAutoHint: 'Dùng thiết bị thu âm đã chọn trong cài đặt máy tính.',
  microphoneUnnamed: 'Micrô',
  microphoneSuggested: 'Đề xuất',
  microphoneWiredHint: 'Có vẻ là micrô có dây hoặc USB. Một lựa chọn ban đầu cho giọng nói.',
  microphoneBuiltInHint:
    'Có vẻ là micrô tích hợp. Một lựa chọn ban đầu không cần kết nối không dây.',
  microphoneBluetoothHint:
    'Có vẻ dùng Bluetooth. Thời gian khởi động và chất lượng âm thanh có thể thay đổi.',
  microphoneVirtualHint:
    'Có vẻ là thiết bị thu âm ảo. Kiểm tra thiết bị truyền giọng nói của bạn thay vì âm thanh máy tính.',
  microphoneUnknownHint: 'Hãy chọn nếu đây là micrô bạn thường dùng để nói.',
  microphoneRecommendationHint:
    'Đề xuất dựa trên tên thiết bị, chưa kiểm tra âm thanh. Lựa chọn phù hợp tùy thuộc thiết bị và môi trường của bạn.',
  microphoneNextHoldHint:
    'Lựa chọn được lưu trên thiết bị này và áp dụng cho lần giữ phím tiếp theo. Mở danh sách không thu âm.',
  microphonePermissionHint:
    'Chưa có thiết bị được đặt tên. Giữ phím tắt nói một lần để cấp quyền micrô rồi làm mới. Kiểm tra quyền micrô trong cài đặt máy tính.',
  microphoneUnavailable:
    'Micrô đã chọn không khả dụng. Kết nối lại, chọn thiết bị khác hoặc Tự động chọn. Tro sẽ không tự đổi thiết bị.',
  microphoneListError:
    'Không thể liệt kê micrô. Kiểm tra quyền micrô của hệ điều hành rồi làm mới.',
  microphoneStorageWarning:
    'Lựa chọn có hiệu lực trong phiên này nhưng không thể lưu trên thiết bị.',
  microphoneVoiceError:
    'Không thể bắt đầu hoặc hoàn tất nhập giọng nói. Kiểm tra micrô và quyền hệ điều hành rồi thử lại.',
  microphoneRetryVoice: 'Thử khởi động giọng nói lại',
  microphoneSignInHint: 'Đăng nhập để chọn micrô.',
  microphoneRefresh: 'Làm mới thiết bị',
  microphoneDone: 'Xong',
  microphonePreferred: 'Ưu tiên',
  microphoneEditRanking: 'Sửa thứ tự ưu tiên',
  microphoneResetRanking: 'Đặt lại thứ tự',
  microphoneRankingHint:
    'Micrô khả dụng đầu tiên trong thứ tự của bạn được ưu tiên. Thứ tự không thay đổi micrô đã chọn hoặc chế độ Tự động chọn.',
  microphoneMoveUp: (name: string): string => `Đưa ${name} lên`,
  microphoneMoveDown: (name: string): string => `Đưa ${name} xuống`,
  microphoneCompare: 'So sánh micrô',
  microphoneTestPrivacy:
    'Mỗi lần thử mở một micrô trong sáu giây. Âm thanh được đo ngay trên máy, không tải lên hoặc lưu lại. Đóng hộp thoại hoặc hủy để dừng.',
  microphoneTestInstructions:
    'Với mỗi micrô: giữ im lặng hai giây, rồi đọc cùng một câu trong bốn giây. Giữ nguyên vị trí và môi trường. Nhấn giữ để nói tạm dừng khi thử.',
  microphoneTestPhrase: '“Đây là bài thử micrô. Tôi muốn giọng nói của mình rõ ràng.”',
  microphoneTestDevice: (name: string): string => `Thử ${name}`,
  microphoneTestOpening: 'Đang mở micrô…',
  microphoneTestQuiet: 'Giữ im lặng',
  microphoneTestSpeak: 'Nói ngay bây giờ',
  microphoneTestCancel: 'Hủy bài thử',
  microphoneTestBusy: 'Hoàn tất lệnh giọng nói hoặc tác vụ hiện tại trước khi thử.',
  microphoneTestError:
    'Không thể hoàn tất bài thử. Kiểm tra quyền micrô và thiết bị đang kết nối rồi thử lại.',
  microphoneTestLimitations:
    'Ít tiếng ồn khi im lặng và ít méo do quá mức có thể hữu ích. Nói to hơn không luôn tốt hơn. Các mức này bao gồm xử lý của thiết bị, không đo độ chính xác chuyển giọng nói thành chữ. Tự chọn hoặc xếp thứ tự; kết quả xóa khi đổi thiết bị hoặc đăng xuất.',
  microphoneNoise: 'Ồn khi im lặng',
  microphoneSpeech: 'Mức giọng nói',
  microphoneClipping: 'Quá mức',
  microphoneStartup: 'Khởi động',
  microphoneChange: 'Chọn micrô',

  taskSucceeded: 'Đã hoàn tất yêu cầu',
  taskPartial: 'Đã hoàn tất một phần',
  taskBlocked: 'Không thể tiếp tục',
  taskUnverified: 'Chưa xác nhận được kết quả',
  navigation: 'Điều hướng chính',
  workspace: 'Không gian làm việc',
  settings: 'Cài đặt',
  yourAccount: 'Tài khoản của bạn',
  checkingSignIn: 'Đang kiểm tra đăng nhập…',
  signOut: 'Đăng xuất',
  ownWorkspace: 'Không gian làm việc của riêng bạn',
  signInInvitation: 'Đăng nhập để bắt đầu.',
  signIn: 'Đăng nhập',
  attention: 'Có vấn đề cần xử lý',
  settingsGeneral: 'Chung',
  settingsNavigation: 'Nhóm cài đặt',
  settingsClose: 'Đóng cài đặt',
  settingsShortcut: 'Phím tắt nói',
  settingsShortcutHint: 'Giữ để nói, thả để gửi.',
  settingsShortcutUnavailable: 'Phím tắt chưa khả dụng. Bạn có thể nhập tin nhắn.',
  settingsMicrophoneUnavailable: 'Chưa kết nối',
  account: 'Tài khoản',
  name: 'Tên',
  email: 'Email',
  signOutHint: 'Bạn có thể đăng xuất ở thanh bên.',
  accountSignInHint: 'Đăng nhập ở thanh bên để xem tài khoản của bạn.',
  appearance: 'Giao diện',
  appearanceDescription: 'Giao diện sáng, đơn giản và ấm áp.',
  light: 'Sáng',
  language: 'Ngôn ngữ',
  languageDescription: 'Ngôn ngữ hiển thị, lưu trên thiết bị này.',
  languageStorageWarning: 'Đã đổi ngôn ngữ cho lần sử dụng này, nhưng không thể lưu trên thiết bị.',
  assistant: 'Trợ lý sử dụng máy tính',
  welcome: (name: string): string => `Chào mừng trở lại, ${name}`,
  workspaceHeading: 'Một không gian nhỏ, làm được nhiều hơn.',
  workspaceDescription: 'Máy tính của bạn, có thêm một người trợ giúp.',
  taskMode: 'Cách Tro hỗ trợ',
  showMe: 'Hướng dẫn tôi',
  doIt: 'Làm giúp tôi',
  stopTask: 'Dừng',
  cancelLesson: 'Esc',
  teachingDisclosure:
    'Tro hiển thị hướng dẫn; bạn điều khiển chuột và bàn phím. Tro có thể đưa ứng dụng đang mở lên trước. Nội dung màn hình gửi đến OpenAI sẽ rời khỏi máy tính. Hiện hướng dẫn hỗ trợ màn hình chính trên macOS.',
  errorCompanionUnavailable:
    'Hướng dẫn con trỏ chưa khả dụng. Hãy cập nhật hoặc cài lại Tro rồi thử lại.',
  newTask: 'Tác vụ mới',
  makeYourselfAtHome: 'Chào mừng bạn đến với Tro.',
  googleInvitation: 'Đăng nhập để bắt đầu tác vụ với Tro. Google sẽ mở trong trình duyệt của bạn.',
  waitingForGoogle: 'Đang chờ Google…',
  continueWithGoogle: 'Tiếp tục với Google',
  helpHeading: 'Tôi có thể giúp gì cho bạn?',
  helpDescription:
    'Đặt câu hỏi hoặc cho Tro biết bạn muốn làm gì trong một ứng dụng trên máy tính.',
  conversation: 'Cuộc trò chuyện',
  you: 'Bạn',
  yourMessage: 'Tin nhắn của bạn',
  messagePlaceholder: 'Nhờ Tro giúp bạn một việc…',
  working: 'Tro đang làm việc trên máy tính của bạn…',
  freshStart: 'Mỗi tin nhắn là một tác vụ mới',
  sendToTro: 'Gửi cho Tro',
  send: 'Gửi',
  taskDisclosure:
    'Tro có thể xem màn hình và sử dụng chuột hoặc bàn phím của bạn. Nội dung màn hình gửi đến OpenAI sẽ rời khỏi máy tính của bạn. Mỗi tin nhắn là một tác vụ mới; cuộc trò chuyện này sẽ được xóa khi bạn đóng ứng dụng.',
  errorCheckSignIn: 'Không thể kiểm tra đăng nhập. Vui lòng thử đăng nhập lại.',
  errorSignInTimeout: 'Đăng nhập Google chưa hoàn tất. Vui lòng thử lại.',
  errorSignInCallback:
    'Tro không thể nhận kết quả đăng nhập. Đóng các ứng dụng Tro khác và khởi động lại trình chạy này, rồi thử lại.',
  errorOpenGoogle: 'Không thể mở đăng nhập Google.',
  errorClearTask: 'Không thể xóa tác vụ. Vui lòng thử lại.',
  errorStartTask: 'Không thể bắt đầu tác vụ. Vui lòng thử lại.',
  errorDailyModelLimit:
    'Bạn đã dùng hết lượt mô hình hôm nay. Hãy thử lại sau khi hạn mức được đặt lại.',
  errorCompleteTask: 'Không thể hoàn tất tác vụ. Hãy kiểm tra kết nối và quyền truy cập máy tính.',
  errorContactAgent: 'Không thể kết nối với trợ lý trên máy tính. Vui lòng gửi lại.',
  errorSignOut: 'Không thể đăng xuất. Vui lòng thử lại.',
  errorSignInService: 'Không thể kết nối với dịch vụ đăng nhập.',
  errorGoogleConfiguration: 'Máy chủ chưa được cấu hình để đăng nhập Google.',
  errorSignInRequired: 'Đăng nhập để sử dụng Tro.',
  errorTaskBusy: 'Hãy chờ tác vụ hiện tại hoàn tất.',
  errorAgentActive: 'Một phiên trợ lý đang hoạt động.',
  errorAgentStopped: 'Phiên trợ lý đã kết thúc. Hãy bắt đầu tác vụ mới.',
  errorAgentTimeout: 'Yêu cầu gửi đến trợ lý đã hết thời gian chờ. Vui lòng thử lại.',
  guidanceWaiting: 'Đang chờ bạn thực hiện bước tiếp theo',
  guidanceAwaitingAnswer: 'Trả lời để tiếp tục',
  guidancePaused: 'Yêu cầu chưa hoàn tất; đang tạm dừng',
  guidanceGoalReached: 'Đã hoàn tất yêu cầu',
  guidanceDemonstrated: 'Đã hiển thị hướng dẫn',
  guidanceNeedsInput: 'Cần bạn hỗ trợ',
  guidanceCanceled: 'Đã dừng hướng dẫn',
  guidanceFailed: 'Chưa hoàn tất hướng dẫn',
  guidanceNeedsInputMessage:
    'Bạn muốn mình chỉ trong ứng dụng hay màn hình nào? Hãy mở trên màn hình chính và cho mình biết bạn muốn thử làm gì.',
  guidanceCanceledMessage: 'Hướng dẫn đã dừng. Hãy gửi yêu cầu mới khi bạn muốn tiếp tục.',
  guidanceFailedMessage:
    'Tro chưa thể hoàn tất hướng dẫn trực quan. Hãy gửi yêu cầu mới để thử lại.',
  guidanceTargetChangedMessage:
    'Màn hình đã thay đổi hoặc ảnh chụp hết hạn trước khi mình kịp minh họa. Bạn có thể giữ mục tiêu hiển thị trên màn hình chính và yêu cầu mình chỉ lại bước đó không?',
  errorDesktopPermissions:
    'Không thể bắt đầu điều khiển máy tính. Hãy cấp quyền Ghi màn hình và Trợ năng cho Tro trong Cài đặt hệ thống, rồi thử lại.',
  errorDesktopStart:
    'Không thể bắt đầu điều khiển máy tính. Hãy khởi động lại Tro hoặc cài đặt lại ứng dụng, rồi thử lại.',
  errorInvalidRequest: 'Yêu cầu này không hợp lệ. Vui lòng thử lại.',
  errorWindowAccess:
    'Cửa sổ này không có quyền thực hiện thao tác. Hãy khởi động lại Tro và thử lại.',
  permissionSetup: 'Thiết lập quyền truy cập máy tính',
  permissionProgress: 'Bước thiết lập 2 trong 3',
  permissionMacAccess: '2 Quyền trên Mac',
  permissionReady: '3 Sẵn sàng',
  permissionOneTimeSetup: 'THIẾT LẬP MỘT LẦN',
  permissionHeading: 'Cho phép Tro truy cập máy tính của bạn.',
  permissionIntroduction:
    'Tro cần hai quyền trên macOS để xem màn hình và hỗ trợ bạn trong các ứng dụng. Bạn có thể quản lý các quyền này trong Cài đặt hệ thống.',
  permissionTitle: 'Quyền truy cập máy tính',
  permissionBothNeeded: 'Cần cả hai quyền để hỗ trợ trên máy tính',
  permissionAccessibility: 'Trợ năng',
  permissionAccessibilityDescription: 'Cho phép Tro tương tác với ứng dụng bạn đang dùng.',
  permissionScreenRecording: 'Ghi màn hình',
  permissionScreenRecordingDescription: 'Cho phép Tro xem nội dung trên màn hình.',
  permissionEnabled: 'Đã bật',
  permissionMissing: 'Chưa bật',
  permissionUnknown: 'Chưa xác minh',
  permissionOpenSettings: 'Mở Cài đặt',
  permissionRequest: 'Yêu cầu quyền truy cập',
  permissionCheckAgain: 'Kiểm tra lại',
  permissionChecking: 'Đang kiểm tra Tro…',
  permissionReturnHint:
    'Sau khi bật cả hai quyền, hãy quay lại Tro. Ứng dụng sẽ tự động kiểm tra lại.',
  permissionRestartHint:
    'Bạn có thể cần đóng rồi mở lại Tro sau khi thay đổi quyền Ghi màn hình. Tro sẽ chờ xác minh quyền trước khi khởi chạy trợ lý.',
  permissionVerifyError: 'Không thể xác minh quyền của Tro. Vui lòng thử lại.',
  permissionSettingsHint:
    'Trong Cài đặt hệ thống, hãy bật cả hai quyền cho Tro rồi quay lại Tro. Khi phát triển, ứng dụng có thể có tên Electron.',
  permissionRequestError:
    'Không thể mở thiết lập quyền trên macOS. Hãy mở Cài đặt hệ thống theo cách thủ công.',
  permissionOpenError:
    'Không thể mở Cài đặt hệ thống. Hãy mở Quyền riêng tư & Bảo mật theo cách thủ công.',
} satisfies TranslationCatalog;
