import type { TranslationCatalog } from './English.js';

export const vietnamese = {
  voiceDisclosure:
    'Khi bạn giữ phím tắt hoặc nút Nói, Tro gửi âm thanh từ micrô đến OpenAI. Thả để tự động gửi chỉ dẫn đã nhận dạng cho trợ lý. Sử dụng ngôn ngữ hiện tại. Nhấn Escape để hủy. Âm thanh và bản chép lời không được lưu trên thiết bị.',
  voiceStarting: 'Đang chuẩn bị nhập bằng giọng nói…',
  voiceUnavailable: 'Nhập bằng giọng nói chưa khả dụng. Kiểm tra quyền micrô rồi thử lại.',
  voiceCheckAgain: 'Kiểm tra lại quyền giọng nói',
  voiceShortcutUnavailable:
    'Phím tắt toàn hệ thống chưa khả dụng. Trên Mac, cấp quyền Trợ năng cho Tro trong Cài đặt hệ thống rồi kiểm tra lại quyền giọng nói. Khi phát triển, ứng dụng có tên Electron. Quyền của CuaDriver là riêng biệt. Bạn vẫn có thể dùng nút Nói.',
  voiceError:
    'Không thể hoàn tất nhập bằng giọng nói. Kiểm tra quyền micrô, kết nối và hạn mức giọng nói rồi thử lại.',
  voicePreparing: 'Đang chuẩn bị micrô…',
  voiceRecording: 'Đang nghe… thả để gửi',
  voiceFinalizing: 'Đang hoàn tất bản chép lời…',
  voiceReady: 'Giữ để nói; thả để gửi',
  voiceTalk: 'Giữ để nói',
  voiceCancel: 'Hủy ghi âm',

  navigation: 'Điều hướng chính',
  workspace: 'Không gian làm việc',
  settings: 'Cài đặt',
  yourAccount: 'Tài khoản của bạn',
  checkingSignIn: 'Đang kiểm tra đăng nhập…',
  signOut: 'Đăng xuất',
  ownWorkspace: 'Không gian làm việc của riêng bạn',
  signInInvitation: 'Đăng nhập để bắt đầu.',
  signIn: 'Đăng nhập',
  yourDesktop: 'MÁY TÍNH CỦA BẠN',
  attention: 'Có vấn đề cần xử lý',
  settingsDescription: 'Mọi cài đặt cần thiết ở cùng một nơi.',
  account: 'Tài khoản',
  name: 'Tên',
  email: 'Email',
  signOutHint: 'Bạn có thể đăng xuất ở thanh bên.',
  accountSignInHint: 'Đăng nhập ở thanh bên để xem tài khoản của bạn.',
  appearance: 'Giao diện',
  appearanceDescription: 'Giao diện sáng, đơn giản và ấm áp.',
  light: 'Sáng',
  language: 'Ngôn ngữ',
  languageDescription:
    'Chọn ngôn ngữ hiển thị của Tro. Thay đổi có hiệu lực ngay và được lưu trên thiết bị này.',
  languageStorageWarning: 'Đã đổi ngôn ngữ cho lần sử dụng này, nhưng không thể lưu trên thiết bị.',
  assistant: 'Trợ lý sử dụng máy tính',
  welcome: (name: string): string => `Chào mừng trở lại, ${name}`,
  workspaceHeading: 'Một không gian nhỏ, làm được nhiều hơn.',
  workspaceDescription: 'Máy tính của bạn, có thêm một người trợ giúp.',
  taskMode: 'Cách Tro hỗ trợ',
  showMe: 'Hướng dẫn tôi',
  doIt: 'Làm giúp tôi',
  stopTask: 'Dừng',
  teachingDisclosure:
    'Tro hiển thị hướng dẫn; bạn điều khiển chuột và bàn phím. Tro có thể đưa ứng dụng đang mở lên trước. Nội dung màn hình gửi đến OpenAI sẽ rời khỏi máy tính. Hiện hướng dẫn hỗ trợ màn hình chính trên macOS.',
  errorCompanionUnavailable:
    'Hướng dẫn con trỏ chưa khả dụng. Hãy cập nhật hoặc cài lại Tro rồi thử lại.',
  newTask: 'Tác vụ mới',
  makeYourselfAtHome: 'Chào mừng bạn đến với Tro.',
  googleInvitation: 'Đăng nhập để bắt đầu tác vụ với Tro. Google sẽ mở trong trình duyệt của bạn.',
  waitingForGoogle: 'Đang chờ Google…',
  continueWithGoogle: 'Tiếp tục với Google',
  helpHeading: 'Tôi có thể giúp gì cho bạn?',
  helpDescription:
    'Đặt câu hỏi hoặc cho Tro biết bạn muốn làm gì trong một ứng dụng trên máy tính.',
  conversation: 'Cuộc trò chuyện',
  you: 'Bạn',
  yourMessage: 'Tin nhắn của bạn',
  messagePlaceholder: 'Nhờ Tro giúp bạn một việc…',
  working: 'Tro đang làm việc trên máy tính của bạn…',
  freshStart: 'Mỗi tin nhắn là một tác vụ mới',
  sendToTro: 'Gửi cho Tro',
  send: 'Gửi',
  taskDisclosure:
    'Tro có thể xem màn hình và sử dụng chuột hoặc bàn phím của bạn. Nội dung màn hình gửi đến OpenAI sẽ rời khỏi máy tính của bạn. Mỗi tin nhắn là một tác vụ mới; cuộc trò chuyện này sẽ được xóa khi bạn đóng ứng dụng.',
  errorCheckSignIn: 'Không thể kiểm tra đăng nhập. Vui lòng thử đăng nhập lại.',
  errorSignInTimeout: 'Đăng nhập Google chưa hoàn tất. Vui lòng thử lại.',
  errorOpenGoogle: 'Không thể mở đăng nhập Google.',
  errorClearTask: 'Không thể xóa tác vụ. Vui lòng thử lại.',
  errorStartTask: 'Không thể bắt đầu tác vụ. Vui lòng thử lại.',
  errorDailyModelLimit:
    'Bạn đã dùng hết lượt mô hình hôm nay. Hãy thử lại sau khi hạn mức được đặt lại.',
  errorCompleteTask: 'Không thể hoàn tất tác vụ. Hãy kiểm tra kết nối và quyền truy cập máy tính.',
  errorContactAgent: 'Không thể kết nối với trợ lý trên máy tính. Vui lòng gửi lại.',
  errorSignOut: 'Không thể đăng xuất. Vui lòng thử lại.',
  errorSignInService: 'Không thể kết nối với dịch vụ đăng nhập.',
  errorGoogleConfiguration: 'Máy chủ chưa được cấu hình để đăng nhập Google.',
  errorSignInRequired: 'Đăng nhập để sử dụng Tro.',
  errorTaskBusy: 'Hãy chờ tác vụ hiện tại hoàn tất.',
  errorAgentActive: 'Một phiên trợ lý đang hoạt động.',
  errorAgentStopped: 'Phiên trợ lý đã kết thúc. Hãy bắt đầu tác vụ mới.',
  errorAgentTimeout: 'Yêu cầu gửi đến trợ lý đã hết thời gian chờ. Vui lòng thử lại.',
  errorDesktopPermissions:
    'Không thể bắt đầu điều khiển máy tính. Hãy cấp quyền Ghi màn hình và Trợ năng cho CuaDriver trong Cài đặt hệ thống, rồi thử lại.',
  errorDesktopStart:
    'Không thể bắt đầu điều khiển máy tính. Hãy khởi động lại Tro hoặc cài đặt lại ứng dụng, rồi thử lại.',
  errorInvalidRequest: 'Yêu cầu này không hợp lệ. Vui lòng thử lại.',
  errorWindowAccess:
    'Cửa sổ này không có quyền thực hiện thao tác. Hãy khởi động lại Tro và thử lại.',
  permissionSetup: 'Thiết lập quyền truy cập máy tính',
  permissionProgress: 'Bước thiết lập 2 trong 3',
  permissionMacAccess: '2 Quyền trên Mac',
  permissionReady: '3 Sẵn sàng',
  permissionOneTimeSetup: 'THIẾT LẬP MỘT LẦN',
  permissionHeading: 'Cho phép Tro truy cập máy tính của bạn.',
  permissionIntroduction:
    'CuaDriver cần hai quyền trên macOS để xem màn hình và hỗ trợ bạn trong các ứng dụng. Bạn có thể quản lý các quyền này trong Cài đặt hệ thống.',
  permissionTitle: 'Quyền truy cập máy tính',
  permissionBothNeeded: 'Cần cả hai quyền để hỗ trợ trên máy tính',
  permissionAccessibility: 'Trợ năng',
  permissionAccessibilityDescription: 'Cho phép CuaDriver tương tác với ứng dụng bạn đang dùng.',
  permissionScreenRecording: 'Ghi màn hình',
  permissionScreenRecordingDescription: 'Cho phép CuaDriver xem nội dung trên màn hình.',
  permissionEnabled: 'Đã bật',
  permissionMissing: 'Chưa bật',
  permissionUnknown: 'Chưa xác minh',
  permissionOpenSettings: 'Mở Cài đặt',
  permissionRequest: 'Yêu cầu quyền truy cập',
  permissionCheckAgain: 'Kiểm tra lại',
  permissionChecking: 'Đang kiểm tra CuaDriver…',
  permissionReturnHint:
    'Sau khi bật cả hai quyền, hãy quay lại Tro. Ứng dụng sẽ tự động kiểm tra lại.',
  permissionRestartHint:
    'Bạn có thể cần đóng rồi mở lại CuaDriver sau khi thay đổi quyền Ghi màn hình. Tro sẽ chờ xác minh quyền trước khi khởi chạy trợ lý.',
  permissionVerifyError: 'Không thể xác minh quyền của CuaDriver. Vui lòng thử lại.',
  permissionSettingsHint:
    'Trong Cài đặt hệ thống, hãy bật cả hai quyền cho CuaDriver rồi quay lại Tro.',
  permissionRequestError:
    'Không thể mở thiết lập quyền trên macOS. Hãy mở Cài đặt hệ thống theo cách thủ công.',
  permissionOpenError:
    'Không thể mở Cài đặt hệ thống. Hãy mở Quyền riêng tư & Bảo mật theo cách thủ công.',
} satisfies TranslationCatalog;
