import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { format, resolveConfig } from 'prettier';

/** Identity covers trusted presentation/schema source, pinned renderer and font bytes, independent of bundler timestamps. */
export async function writeLessonPresentationIdentity(root: string) {
  const hash = createHash('sha256');
  for (const name of [
    'src/lessonMedia/LessonComposition.tsx',
    'src/lessonMedia/RegisterLessonComposition.tsx',
    'src/contracts/GuidedLessons.ts',
  ]) {
    hash.update(name).update(await readFile(join(root, name)));
  }
  hash.update('remotion@4.0.534');
  hash.update('chrome-for-testing');
  const fonts = createHash('sha256');
  for (const family of ['noto-sans', 'noto-sans-mono']) {
    const directory = join(root, 'node_modules/@fontsource', family, 'files');
    for (const name of (await readdir(directory))
      .filter((name) => /(?:latin|vietnamese)-(?:400|700)-normal\.woff2$/.test(name))
      .sort()) {
      fonts.update(name).update(await readFile(join(directory, name)));
    }
  }
  const identity = {
    compositionBundleHash: hash.digest('hex'),
    fontBundleHash: fonts.digest('hex'),
    rendererVersion: 'remotion-4.0.534:guided-1.0.0',
  };
  const source = await format(
    `/** Generated by the build; matches the trusted source and pinned font bytes. */\nexport const LessonPresentationIdentity = ${JSON.stringify(identity, null, 2)} as const;\n`,
    { ...(await resolveConfig(join(root, 'package.json'))), parser: 'typescript' },
  );
  await writeFile(join(root, 'src/lessonMedia/PresentationIdentity.ts'), source);
  return identity;
}
