/** Generated by the build; matches the trusted source and pinned font bytes. */
export const LessonPresentationIdentity = {
  compositionBundleHash: '6f81aa9052c9bf1950daafee84ed41aee8d5dddbe6e6c6b30cb31273b4d2ae23',
  fontBundleHash: 'be45f3ffd9e719a127a40a5f44b3016691fce3fbf158276e425a6a88ae116f25',
  rendererVersion: 'remotion-4.0.534:guided-1.0.0',
} as const;
