/** Generated by the build; matches the trusted source and pinned font bytes. */
export const LessonPresentationIdentity = {
  compositionBundleHash: '9fde5e56989d3103fc602c077b6582ff740cbf683cde0e010c2607c8ec4b47e1',
  fontBundleHash: 'be45f3ffd9e719a127a40a5f44b3016691fce3fbf158276e425a6a88ae116f25',
  rendererVersion: 'remotion-4.0.534:guided-1.0.0',
} as const;
